"""Jour 10 - Ajout table emplois_du_temps

Revision ID: 2eb03a675dcd
Revises: 44380486d062
Create Date: 2026-04-27 19:17:50.534916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2eb03a675dcd'
down_revision = '44380486d062'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emplois_du_temps',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('enseignant_id', sa.String(length=36), nullable=False),
    sa.Column('jour_semaine', sa.Integer(), nullable=False),
    sa.Column('nom_cours', sa.String(length=200), nullable=False),
    sa.Column('groupe', sa.String(length=50), nullable=True),
    sa.Column('salle', sa.String(length=100), nullable=True),
    sa.Column('heure_debut', sa.Time(), nullable=False),
    sa.Column('heure_fin', sa.Time(), nullable=False),
    sa.Column('tolerance_retard_minutes', sa.Integer(), nullable=False),
    sa.Column('est_actif', sa.Boolean(), nullable=False),
    sa.Column('date_debut_validite', sa.Date(), nullable=True),
    sa.Column('date_fin_validite', sa.Date(), nullable=True),
    sa.Column('cree_le', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['enseignant_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('personnes', schema=None) as batch_op:
        batch_op.alter_column('tolerance_retard_minutes',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('10'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personnes', schema=None) as batch_op:
        batch_op.alter_column('tolerance_retard_minutes',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('10'))

    op.drop_table('emplois_du_temps')
    # ### end Alembic commands ###
