"""Jour 9 - Contrat employe, jours feries, tolerance session, modification presence

Revision ID: 44380486d062
Revises: 524ef1a89723
Create Date: 2026-04-27 10:15:37.620600

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '44380486d062'
down_revision = '524ef1a89723'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jours_feries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('type_ferie', sa.String(length=20), nullable=False),
    sa.Column('cree_par', sa.String(length=36), nullable=True),
    sa.Column('cree_le', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cree_par'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    with op.batch_alter_table('configuration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tolerance_retard_defaut', sa.Integer(), nullable=False, server_default='10'))
    with op.batch_alter_table('personnes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type_contrat', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('date_debut_contrat', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('date_fin_contrat', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('heure_arrivee', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('heure_depart', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('pause_minutes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tolerance_retard_minutes', sa.Integer(), nullable=False, server_default='10'))
        batch_op.add_column(sa.Column('travaille_lundi', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('travaille_mardi', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('travaille_mercredi', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('travaille_jeudi', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('travaille_vendredi', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('travaille_samedi', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('travaille_dimanche', sa.Boolean(), nullable=True))

    with op.batch_alter_table('presences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modifie_par', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('modifie_le', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('justification_modification', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('heures_travaillees', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('heures_supplementaires', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('justification_absence', sa.String(length=50), nullable=True))
        batch_op.create_foreign_key(None, 'utilisateurs', ['modifie_par'], ['id'])

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tolerance_retard_minutes', sa.Integer(), nullable=False, server_default='10'))
        batch_op.add_column(sa.Column('type_session', sa.String(length=20), nullable=False, server_default='cours'))
        batch_op.add_column(sa.Column('personne_id', sa.String(length=36), nullable=True))
        batch_op.alter_column('heure_fin',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.create_foreign_key(None, 'personnes', ['personne_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('heure_fin',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.drop_column('personne_id')
        batch_op.drop_column('type_session')
        batch_op.drop_column('tolerance_retard_minutes')

    with op.batch_alter_table('presences', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('justification_absence')
        batch_op.drop_column('heures_supplementaires')
        batch_op.drop_column('heures_travaillees')
        batch_op.drop_column('justification_modification')
        batch_op.drop_column('modifie_le')
        batch_op.drop_column('modifie_par')

    with op.batch_alter_table('personnes', schema=None) as batch_op:
        batch_op.drop_column('travaille_dimanche')
        batch_op.drop_column('travaille_samedi')
        batch_op.drop_column('travaille_vendredi')
        batch_op.drop_column('travaille_jeudi')
        batch_op.drop_column('travaille_mercredi')
        batch_op.drop_column('travaille_mardi')
        batch_op.drop_column('travaille_lundi')
        batch_op.drop_column('tolerance_retard_minutes')
        batch_op.drop_column('pause_minutes')
        batch_op.drop_column('heure_depart')
        batch_op.drop_column('heure_arrivee')
        batch_op.drop_column('date_fin_contrat')
        batch_op.drop_column('date_debut_contrat')
        batch_op.drop_column('type_contrat')

    with op.batch_alter_table('configuration', schema=None) as batch_op:
        batch_op.drop_column('tolerance_retard_defaut')

    op.drop_table('jours_feries')
    # ### end Alembic commands ###
