"""Jour 5 - models complet en francais + optimistic locking

Revision ID: 44a214631322
Revises: 
Create Date: 2026-04-23 20:18:43.434546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44a214631322'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuration',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('seuil_similarite', sa.Float(), nullable=False),
    sa.Column('max_tentatives', sa.Integer(), nullable=False),
    sa.Column('duree_retention_jours', sa.Integer(), nullable=False),
    sa.Column('langue_defaut', sa.String(length=5), nullable=False),
    sa.Column('email_developpeur', sa.String(length=150), nullable=True),
    sa.Column('email_admin', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('utilisateurs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('mot_de_passe_hache', sa.String(length=255), nullable=False),
    sa.Column('departement', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('role_souhaite', sa.String(length=50), nullable=True),
    sa.Column('statut_compte', sa.String(length=20), nullable=False),
    sa.Column('raison_rejet', sa.String(length=255), nullable=True),
    sa.Column('token_email', sa.String(length=255), nullable=True),
    sa.Column('expiration_token', sa.DateTime(), nullable=True),
    sa.Column('valide_par', sa.String(length=36), nullable=True),
    sa.Column('valide_le', sa.DateTime(), nullable=True),
    sa.Column('tentatives_echouees', sa.Integer(), nullable=True),
    sa.Column('est_actif', sa.Boolean(), nullable=True),
    sa.Column('derniere_connexion', sa.DateTime(), nullable=True),
    sa.Column('cree_le', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['valide_par'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('personnes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('identifiant', sa.String(length=100), nullable=False),
    sa.Column('departement', sa.String(length=100), nullable=True),
    sa.Column('niveau_ou_poste', sa.String(length=100), nullable=True),
    sa.Column('groupe_ou_site', sa.String(length=100), nullable=True),
    sa.Column('est_actif', sa.Boolean(), nullable=True),
    sa.Column('cree_par', sa.String(length=36), nullable=True),
    sa.Column('cree_le', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cree_par'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('identifiant')
    )
    op.create_table('sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('cree_par', sa.String(length=36), nullable=True),
    sa.Column('lieu', sa.String(length=200), nullable=True),
    sa.Column('heure_debut', sa.DateTime(), nullable=False),
    sa.Column('heure_fin', sa.DateTime(), nullable=True),
    sa.Column('cree_le', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cree_par'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cartes_rfid',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('numero_rfid', sa.String(length=255), nullable=False),
    sa.Column('personne_id', sa.String(length=36), nullable=False),
    sa.Column('statut', sa.String(length=20), nullable=False),
    sa.Column('attribuee_par', sa.String(length=36), nullable=True),
    sa.Column('attribuee_le', sa.DateTime(), nullable=True),
    sa.Column('revoquee_le', sa.DateTime(), nullable=True),
    sa.Column('raison_revocation', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['attribuee_par'], ['utilisateurs.id'], ),
    sa.ForeignKeyConstraint(['personne_id'], ['personnes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_rfid')
    )
    op.create_table('photos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('personne_id', sa.String(length=36), nullable=False),
    sa.Column('chemin_fichier', sa.String(length=255), nullable=False),
    sa.Column('est_principale', sa.Boolean(), nullable=True),
    sa.Column('score_qualite', sa.Float(), nullable=True),
    sa.Column('est_chiffree', sa.Boolean(), nullable=True),
    sa.Column('cree_le', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['personne_id'], ['personnes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('journal_securite',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('horodatage', sa.DateTime(), nullable=True),
    sa.Column('type_evenement', sa.String(length=100), nullable=False),
    sa.Column('severite', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('adresse_ip', sa.String(length=50), nullable=True),
    sa.Column('resultat', sa.String(length=20), nullable=True),
    sa.Column('destinataire', sa.String(length=20), nullable=False),
    sa.Column('utilisateur_id', sa.String(length=36), nullable=True),
    sa.Column('personne_id', sa.String(length=36), nullable=True),
    sa.Column('carte_rfid_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['carte_rfid_id'], ['cartes_rfid.id'], ),
    sa.ForeignKeyConstraint(['personne_id'], ['personnes.id'], ),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('presences',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('personne_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('carte_rfid_id', sa.String(length=36), nullable=True),
    sa.Column('horodatage', sa.DateTime(), nullable=True),
    sa.Column('score_similarite', sa.Float(), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=False),
    sa.Column('methode_validation', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['carte_rfid_id'], ['cartes_rfid.id'], ),
    sa.ForeignKeyConstraint(['personne_id'], ['personnes.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('presences')
    op.drop_table('journal_securite')
    op.drop_table('photos')
    op.drop_table('cartes_rfid')
    op.drop_table('sessions')
    op.drop_table('personnes')
    op.drop_table('utilisateurs')
    op.drop_table('configuration')
    # ### end Alembic commands ###
