"""Jour 11 - statut session + seuils absences

Revision ID: 5035697bc13d
Revises: a4f1401df2c3
Create Date: 2026-04-29 01:10:51.492948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5035697bc13d'
down_revision = 'a4f1401df2c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seuils_absences',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('niveau', sa.Integer(), nullable=False),
    sa.Column('nb_absences', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('sujet_email', sa.String(length=200), nullable=False),
    sa.Column('message_email', sa.Text(), nullable=False),
    sa.Column('est_actif', sa.Boolean(), nullable=True),
    sa.Column('cree_le', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('statut', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_column('statut')

    op.drop_table('seuils_absences')
    # ### end Alembic commands ###
