"""Jour 8 - Ajout infos etablissement et domaine email dans configuration

Revision ID: 524ef1a89723
Revises: e2bd8ecde1a8
Create Date: 2026-04-26 00:40:20.640436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '524ef1a89723'
down_revision = 'e2bd8ecde1a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nom_etablissement', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('adresse', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('ville', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('telephone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('site_web', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('logo_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('domaine_email_autorise', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuration', schema=None) as batch_op:
        batch_op.drop_column('domaine_email_autorise')
        batch_op.drop_column('logo_path')
        batch_op.drop_column('site_web')
        batch_op.drop_column('telephone')
        batch_op.drop_column('ville')
        batch_op.drop_column('adresse')
        batch_op.drop_column('nom_etablissement')

    # ### end Alembic commands ###
