"""Jour 10 - Ajout table heures_supplementaires

Revision ID: a4f1401df2c3
Revises: 2eb03a675dcd
Create Date: 2026-04-27 19:37:35.589096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4f1401df2c3'
down_revision = '2eb03a675dcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('heures_supplementaires',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('personne_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('duree_minutes', sa.Integer(), nullable=False),
    sa.Column('raison', sa.String(length=255), nullable=False),
    sa.Column('saisie_par', sa.String(length=36), nullable=False),
    sa.Column('saisie_le', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['personne_id'], ['personnes.id'], ),
    sa.ForeignKeyConstraint(['saisie_par'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('heures_supplementaires')
    # ### end Alembic commands ###
