"""Pause emploi du temps + champs session

Revision ID: b870efb14371
Revises: 5035697bc13d
Create Date: 2026-05-01 16:21:08.037819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b870efb14371'
down_revision = '5035697bc13d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emplois_du_temps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('a_pause', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('heure_debut_pause', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('duree_pause_minutes', sa.Integer(), nullable=True))

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('emploi_du_temps_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('est_exceptionnelle', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('pause_suspendue', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('reprogrammee_le', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'emplois_du_temps', ['emploi_du_temps_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('reprogrammee_le')
        batch_op.drop_column('pause_suspendue')
        batch_op.drop_column('est_exceptionnelle')
        batch_op.drop_column('emploi_du_temps_id')

    with op.batch_alter_table('emplois_du_temps', schema=None) as batch_op:
        batch_op.drop_column('duree_pause_minutes')
        batch_op.drop_column('heure_debut_pause')
        batch_op.drop_column('a_pause')

    # ### end Alembic commands ###
