"""add departement niveau to emplois_du_temps

Revision ID: bb4d27c16322
Revises: b870efb14371
Create Date: 2026-05-09 00:41:07.975483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb4d27c16322'
down_revision = 'b870efb14371'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emplois_du_temps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('departement', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('niveau', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emplois_du_temps', schema=None) as batch_op:
        batch_op.drop_column('niveau')
        batch_op.drop_column('departement')

    # ### end Alembic commands ###
