"""Jour 8 - Ajout table notifications

Revision ID: e2bd8ecde1a8
Revises: 44a214631322
Create Date: 2026-04-25 23:32:21.853024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2bd8ecde1a8'
down_revision = '44a214631322'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('destinataire_id', sa.String(length=36), nullable=False),
    sa.Column('expediteur_id', sa.String(length=36), nullable=True),
    sa.Column('type_notification', sa.String(length=50), nullable=False),
    sa.Column('titre', sa.String(length=200), nullable=False),
    sa.Column('contenu', sa.Text(), nullable=True),
    sa.Column('est_lue', sa.Boolean(), nullable=False),
    sa.Column('lue_le', sa.DateTime(), nullable=True),
    sa.Column('cree_le', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['destinataire_id'], ['utilisateurs.id'], ),
    sa.ForeignKeyConstraint(['expediteur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications')
    # ### end Alembic commands ###
